<html>
    <head>
        <title>Raport catre Autoritate Nationala </title>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <meta charset="utf-8">
        <style>
        label {
            font-weight: bold;
            color: rgb(109, 112, 114);
        }
        span {
            color: rgb(109, 112, 114);
        }
        </style>
    </head>
    <body>
        <?php
        $text = '';
        if (isset($info)) {
            $text .= '<div style="text-align:center; color: #777;">Report generated by ' . $info->name . ' on behalf od ' . $info->company . '</div>';
        }
        $text .= '<p style="text-align:center;">Acest raport arata progresul conformarii GDPR pe fiecare capitol in parte si poate fi prezentat autoritatii in cazul in care aveti un control sau va sunt solicitate informatii cu privire la actiuniile si eforturiile intreprinse in vederea conformarii. </p>';
        if ($authoritys && count($authoritys)) {
            foreach ($authoritys as $pagename => $list) {
                if (count($list)) {
                    $text .= '<h4>' . $pagename . '</h4>';
                }
                foreach ($list as $li) {
                    $val = str_replace("\u0103", "ă", $li["val"]);
                    $text .= '<div>';
                    $text .= '<label>' . $li["title"] . '</label><br>';
                    $text .= '<span>' . $val . '</span>';
                    $text .= '</div><br>';
                }
            }
        }
        header('Content-Type: text/html; charset=utf-8');
        echo $text;
        ?>
        <script>
            window.print();
            window.close();
        </script>
    </body>
</html>
